---
PATHS:
  settings_pRT: "/net/ipa-gate/export/ipa/quanz/user_accounts/konradb/Virtual_Software/"
  #settings_pRT: "/home/konradb/Documents/"
  settings_multinest: "/"
  settings_opacity_database: "/net/ipa-gate/export/ipa/quanz/user_accounts/konradb/input_data/"
  settings_input_profile: "/net/ipa-gate/export/ipa/quanz/user_accounts/konradb/Retrieval_Inputs/Timmy/PT_Timmy_2.txt"
INPUT FILES:
  settings_data_file: "/net/ipa-gate/export/ipa/quanz/user_accounts/konradb/Retrieval_Inputs/Timmy/Earth_Timmy_R200_ph_SN_10_2.txt"
LAMBDA RANGE:
  WMIN: "3"
  WMAX: "20"
PREFIX:
  settings_prefix: "/Users/timothy/Desktop/projects/pyretlife/configs"
TEMPERATURE PARAMETERS:
  #settings_parametrization: "polynomial"
  #a_4: "U 2 5 T 3.67756393"
  #a_3: "U 0 100 T 40.08733884"
  #a_2: "U 0 300 T 136.42147966"
  #a_1: "U 0 500 T 182.6557084"
  #a_0: "U 0 600 T 292.92802205"
  settings_parametrization: "vae_pt"
  settings_vae_net: "decoder.onnx"
  z_1: "U -4 4 T 1.5 #2.54"
  z_2: "U -4 4 T 0.0 #-0.66"
PHYSICAL PARAMETERS:
  P0: "LU -2 2 T 1.0294"
  d_syst: "10"
  R_pl: "G 1 0.2 T 1 # G 1 0.2 T 1 #G 1 0.2 T"
  M_pl: "LG 0 0.4 T 1 # LG 0 0.4 T 1 #LG 0 0.4 T"
CHEMICAL COMPOSITION PARAMETERS:
  settings_resolution: "200"
  settings_mmw_inert: "28.9 #if not provided, it will be discarded"
  N2: "LU -2 0 T 0.78 #LU -3 0 T 0.79 #LU -3 0 T"
  O2: "LU -2 0 T 0.20 #LU -3 0 T 0.20 #LU -3 0 T"
  CO2: "LU -8 0 T 0.0004 # LU -15 0 T 0.00041 #LU -15 0 T"
  CH4: "LU -8 0 T 0.0000017 # LU -15 0 T 0.0000017 #LU -15 0 T"
  H2O: "LU -8 0 T 0.001 # LU -15 0 T 0.001 #LU -15 0 T"
  O3: "LU -8 0 T 0.0000003 #LU -15 0 T"
  CO: "LU -8 0 T 0.000000125 #LU -15 0 T"
  #N2O_Chubb: "LU -15 0 T 0.00000032 #LU -15 0 T"
SCATTERING PARAMETERS:
  settings_scattering: "False"
  #reflectance: "0.1 #U 0 2 T 0.78"
  #emissivity: "1. #U 0 2 T 0.22"
  #settings_directlight: "True"
  #stellar_temp: "5778."
  #stellar_radius: "1. #rsun"
  #semimajoraxis: "1. #AU"
CLOUD PARAMETERS:
  settings_clouds: "transparent"
OTHER SETTINGS:
  settings_CIA: "False"
  #  settings_moon: "True # true if moon should be included in retrieval model"
  #  T_m: "U 100 500 T 3000  # what is the correct true value? is it the same for all moons?"
  #  R_m: "U 0.01 0.5 T 0.2724 # in earth radii # 1737404.41 m"
  ##R_m: "U 1000000 3000000 T 1737400 # in m"
