
GROUND TRUTH DATA:
  input_profile: /home/ipa/quanz/user_accounts/egarvin/retrievals_folder/input_data/mf_clear.txt
  data_files:
    LIFE:
      path: /home/ipa/quanz/user_accounts/egarvin/retrievals_folder/input_data/life_clear_observation_R50.txt
      unit: micron, erg s-1 Hz-1 m-2

RUN SETTINGS:
  wavelength_range: [4,19]
  output_folder: /home/ipa/quanz/user_accounts/egarvin/retrievals_folder/Terrestrial_Retrieval/template_retrieval
  include_scattering:
    Rayleigh: True
    thermal: True
    direct_light: True
    clouds: False
  include_CIA: True
  resolution: 200
  n_layers: 100

TEMPERATURE PARAMETERS:
  parameterization: polynomial
#  vae_net: decoder.onx
  a_4:
    prior:
      kind: fourth-uniform
      prior_specs:
        fourth_lower: 0.5
        fourth_upper: 1.8
    truth: 1.67377185
  a_3:
    prior:
      kind: uniform
      prior_specs:
        lower: 0.
        upper: 100.
    truth: 23.11941468
  a_2:
    prior:
      kind: uniform
      prior_specs:
        lower: 0.
        upper: 500.
    truth: 99.70313989
  a_1:
    prior:
      kind: uniform
      prior_specs:
        lower: 0.
        upper: 500.
    truth: 146.625709
  a_0:
    prior:
      kind: uniform
      prior_specs:
        lower: 0.
        upper: 1000.
    truth: 285.21811617

PHYSICAL PARAMETERS:
  P0:
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -4
        log_upper: 3
    truth: 1.014
  d_syst:
    truth: 10.
  R_pl:
    prior:
      kind: gaussian
      prior_specs:
        mean: 1
        sigma: 0.2
    truth: 1.
  M_pl:
    prior:
      kind: log-gaussian
      prior_specs:
        log_mean: 0
        log_sigma: 0.4
    truth: 1.

CHEMICAL COMPOSITION PARAMETERS:
  mmw_inert: 28.
  N2:
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -15
        log_upper: 0
    truth: 0.78
  O2:
    lines:
      - O2_main_HN16_HH_Chubb
      - O2_UV
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -15
        log_upper: 0
    truth: 0.20
  CO2:
    lines:
      - CO2_main_HN20_air_C25
      - CO2_UV
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -15
        log_upper: 0
    truth: 0.0041
  CH4:
    lines:
      - CH4_main_HN20_air_C25
      - CH4_UV
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -15
        log_upper: 0
    truth: 0.0000017
  H2O:
    lines:
      - H2O_main_HN20_air_C25
      - H2O_UV
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -15
        log_upper: 0
    truth: 0.001
  O3:
    lines:
      - O3_main_HN20_air_C25
      - O3_UV
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -15
        log_upper: 0
    truth: 3.e-07
  CO:
    lines:
      - CO_main_HN20_air_C25
      - CO_UV
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -15
        log_upper: 0
    truth: 1.23e-7
  N2O:
    lines:
      - N2O_main_HN20_air_C25
      - N2O_UV
    prior:
      kind: log-uniform
      prior_specs:
        log_lower: -15
        log_upper: 0
    truth: 3.2e-7

SCATTERING PARAMETERS: #read when necessary
  reflectance:
    prior:
      kind: uniform
      prior_specs:
        lower: 0.
        upper: 1
    truth: 0.1
  emissivity:
    prior:
      kind: uniform
      prior_specs:
        lower: 0.
        upper: 1
    truth: 1
  geometry: planetary_ave
  stellar_temperature:
    truth: 5778.
  stellar_radius:
    truth: 1.
  semimajor_axis:
    truth: 1.
